install:
  - pushd package
  - python setup.py develop
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt
  - popd
language: python
python:
  - "3.8"
script: coverage run -m unittest discover
after_success: coveralls